site_name: 申达的个人网站
site_author: 申达
site_url: https://shenda.github.io/
site_description: 申达的个人网站
nav:
   - 主页: index.md
   - 文章: 
     - 随笔:
       - 茉莉雨: moliyu.md
       - 镜像: mirror.md
   - 博客:
     - 日记: diary.md
   - 学习笔记: 
     - Swift: swift.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: 关灯

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      peimary: indigo
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: 开灯

